#! -*- coding: utf-8 -*-

from scrapy.item import Item, Field

class Player(Item):
    player_id = Field()
    title = Field()
    roster_status = Field()
    from_year = Field()
    to_year = Field()
    team_id = Field()
    first_name = Field()
    last_name = Field()
    birthdate = Field()
    school = Field()
    country = Field()
    last_affiliation = Field()
    height = Field()
    weight = Field()
    season_exp = Field()
    jersey = Field()
    position = Field()
    dleague_flag = Field()
    draft_year = Field()
    draft_round = Field()
    draft_number = Field()

class Team(Item):
    team_id = Field()
    abbreviation = Field()
    name = Field()

class Shot(Item):
    game_id = Field()
    game_event_id = Field()
    player_id = Field()
    loc_x = Field()
    loc_y = Field()
    shot_attempted_flag = Field()
    shot_made_flag = Field()

class Game(Item): 
    game_id = Field()
    game_date = Field()
    periods = Field()
    home_team_id = Field()
    visitor_team_id = Field()

class PlayerGameStat(Item): 
    game_id = Field()
    player_id = Field()
    ft_pct = Field()
    fg3a = Field()
    ast = Field()
    plus_minus = Field()
    minutes = Field()
    pts = Field()
    fg_pct = Field()
    fg3m = Field()
    oreb = Field()
    fta = Field()
    to = Field()
    fg3_pct = Field()
    pf = Field()
    fgm = Field()
    blk = Field()
    stl = Field()
    reb = Field()
    dreb = Field()
    ftm = Field()
    fga = Field()

class TeamGameStat(Item): 
    game_id = Field()
    team_id = Field()
    ft_pct = Field()
    fg3a = Field()
    ast = Field()
    plus_minus = Field()
    minutes = Field()
    pts = Field()
    fg_pct = Field()
    fg3m = Field()
    oreb = Field()
    fta = Field()
    to = Field()
    fg3_pct = Field()
    pf = Field()
    fgm = Field()
    blk = Field()
    stl = Field()
    reb = Field()
    dreb = Field()
    ftm = Field()
    fga = Field()

class GameRoster(Item): 
    game_id = Field() 
    player_id = Field()
    team_id = Field()

class EventPlayers(Item): 
    game_id = Field()
    game_event_id = Field()
    matchup_id = Field()

class Matchup(Item):     
    game_id = Field()
    matchup_id = Field()
    home_player1_id = Field() 
    home_player2_id = Field() 
    home_player3_id = Field() 
    home_player4_id = Field() 
    home_player5_id = Field()     
    away_player1_id = Field() 
    away_player2_id = Field() 
    away_player3_id = Field() 
    away_player4_id = Field() 
    away_player5_id = Field()  
